name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Run  Docker container
      run: docker run -d -p 80:80 --name miapp my-image-name:latest
    - name: Push  Docker image to Docker-hub
      run: |
       echo dckr_pat_g_odH4bJ-7NkDs0vV9J2pY47w5k  | docker login --username tajamarabde --password-stdin
       docker push tajamarabde/test:tagname

